package com.weatherrisk.api.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * <pre>
 * 參考: <a href="http://blog.didispace.com/springbootmongodb/">Spring Boot MongoDB</a>
 * 
 * 參考: <a href="https://tests4geeks.com/spring-data-boot-mongodb-example/">Spring data boot mongodb example</a>
 * 
 * 待實作: <a href="http://stackoverflow.com/questions/36448921/how-we-create-autogenerated-field-for-mongodb-using-springboot">Auto Increment</a>
 * </pre>
 * 
 * @author tommy.feng
 *
 */
@Document(collection = "attractions")
public class Attraction {

	@Id
	private Long id;
	private String country;
	private String name;
	private Float[] loc;
	
	public Attraction() {
	}

	public Attraction(Long id, String country, String name, Float[] loc) {
		this.id = id;
		this.country = country;
		this.name = name;
		this.loc = loc;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Float[] getLoc() {
		return loc;
	}

	public void setLoc(Float[] loc) {
		this.loc = loc;
	}
	
}
