package com.weatherrisk.api.service;

import static org.springframework.data.mongodb.core.query.Query.*;
import static org.springframework.data.mongodb.core.query.Criteria.*;
import static org.springframework.data.mongodb.core.FindAndModifyOptions.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.mongodb.core.MongoOperations;
import org.springframework.data.mongodb.core.query.Update;
import org.springframework.stereotype.Service;

import com.weatherrisk.api.model.Counter;

/**
 * <pre>
 * 取得指定 collection 下一個序號
 * 
 * 參考: <a href="http://stackoverflow.com/questions/36448921/how-we-create-autogenerated-field-for-mongodb-using-springboot">Auto Increment</a>
 * </pre>
 * 
 * @author tommy.feng
 *
 */
@Service
public class CounterService {
	
	@Autowired
	private MongoOperations mongo;
	
	public Long resetSequence(String collectionName) {
		Counter counter 
			= mongo.findAndModify(
					query(where("_id").is(collectionName)), 
					new Update().set("seq", 0), 
					options().returnNew(true), 
					Counter.class
			  );
		return counter.getSeq();
	}

	public Long getNextSequence(String collectionName) {
		Counter counter 
			= mongo.findAndModify(
					query(where("_id").is(collectionName)), 
					new Update().inc("seq", 1),
					options().returnNew(true), 
					Counter.class
			  );
		return counter.getSeq();
	}
}
